# This Component adds best practice securityContext to the first Container 
# of Deployments, Statefulsets and DeamonSets
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - patch: |-
      - op: replace 
        path: /spec/template/spec/containers/0/securityContext
        value:
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
    target:
      group: apps
      version: v1
